# NumPy 
NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science using Python. Almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

It is bound to several C libraries which makes NumPy one of the fastest libraries in Python.

We will learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you don't have Anaconda, install NumPy by going to your terminal or command prompt and type:**
    
    !pip install numpy
    conda install numpy
    


## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. 

# Numpy Arrays

Numpy arrays essentially of two types: vectors and matrices. Vectors are strictly 1-D arrays and matrices are 2-D (Note: A matrix can still have only one row or one column).

The following cells explain on creation of NumPy arrays.

## Creating NumPy Arrays

### From a Python List

An array can be created by directly converting a list or list of lists:

In [2]:
import numpy as np

In [3]:
arr1 = np.array([])   # create an empty array
arr1

array([], dtype=float64)

In [4]:
my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [5]:
a=np.array(my_list)

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
type(a)   # ndarray is number dimension array

numpy.ndarray

In [8]:
a.ndim  # number of dimensions in the array

1

In [9]:
a.size  # size of an array is the no. of items 

5

In [10]:
a.shape # shape of array

(5,)

#### Arrays can be of n dimensions.

In [11]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] # list of lists
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [12]:
b=np.array(my_matrix) # generates a 2-d array
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
# Array summary
print('The Dimension of array',b.ndim) # dimensions of given array

The Dimension of array 2


In [14]:
print('The size of array:',b.size) # Number of elements in array

The size of array: 12


In [15]:
print('The datatype of element:',b.dtype) # Datatype of elements in array

The datatype of element: int32


In [16]:
print('The type of structure:',type(b))

The type of structure: <class 'numpy.ndarray'>


In [17]:
print('The shape:',a.shape)

The shape: (5,)


In [18]:
b.shape

(3, 4)

In [19]:
arr1= np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
arr1.shape

(2, 2, 3)

## Built-in Methods

There are lots of built-in ways to generate Arrays

### Reshape function

In [21]:
arr2=arr1.reshape((1,3,4))  # reshape function takes the new shape as its argument

In [22]:
arr2.shape

(1, 3, 4)

### arange

Return evenly spaced values within a given interval.

In [23]:
np.arange(15) # end; default start at 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
np.arange(100,2,-4) # start, end and step

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8,   4])

In [25]:
np.arange(0,11,2) # start end and step

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [26]:
import numpy as np

In [27]:
np.zeros(3) # Generates array in 1 dimension with all elements 0

array([0., 0., 0.])

In [28]:
np.zeros((5,5))  # Generates array in 2 diemnsions with all elements 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones(3) # Generates array of 1 dimension where all elements are 1

array([1., 1., 1.])

In [30]:
np.ones((4,5,6)) # Generates array of 3 dimensions where all elements are 1

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

### linspace
Return evenly spaced numbers over a specified interval.

In [31]:
import numpy as np

In [32]:
np.linspace(1,15)  # default 50 observations
# both the start and end are included in the array

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [33]:
np.linspace(5,25,10)  # equally spaced 10 values

array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
       16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ])

In [34]:
# retstep ~ return step computed by linspace

In [35]:
np.linspace(0,25, retstep=True) # Start # end (Here end is included) and default elements are 50

(array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
         2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
         5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
         7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
        10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
        12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
        15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
        17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
        20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
        22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]),
 0.5102040816326531)

In [36]:
np.linspace(0,200,10) # default retstep=False

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

In [37]:
np.linspace(0,200,10,retstep=True)

(array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
         88.88888889, 111.11111111, 133.33333333, 155.55555556,
        177.77777778, 200.        ]),
 22.22222222222222)

### eye

Creates an identity matrix

In [38]:
np.eye(5)   # generates 2d array of (5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
# Create an eye from a zeros array

### Broadcasting in an array

In [40]:
big_one=np.ones((3,4))
print(big_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [41]:
big_one.dtype

dtype('float64')

In [42]:
big_one * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### The ability to access each and every element of an array is known as Broadcasting.

In [43]:
bigger_one=big_one*6 - 2
bigger_one

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [44]:
bigger=np.array(big_one*3 - 0.4, dtype='int')
print(bigger)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [45]:
bigger.dtype

dtype('int32')

In [46]:
type(bigger)

numpy.ndarray

In [47]:
bigger.shape

(3, 4)

In [48]:
bigger/bigger

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
arr1 = np.arange(20)
1/arr1

C:\Users\cnd15\AppData\Local\Temp\ipykernel_11676\3219800275.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr1


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [52]:
arr=np.ones(5)

In [53]:
arr + arr

array([2., 2., 2., 2., 2.])

In [54]:
arr ** arr

array([1., 1., 1., 1., 1.])

### Use of Copy function

In [55]:
arr2 = arr1 # not recommended
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [56]:
arr2[:10] = 30  # using indexing/slicing to modify arr2
arr2

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
arr1

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [58]:
arr3 = arr1.copy() # generate a copy / creates a backup

In [59]:
arr3[10:] = 100
arr3

array([ 30,  30,  30,  30,  30,  30,  30,  30,  30,  30, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [60]:
arr1  # copy function retains the original. copy creates a backup array.

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Random number generation

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [61]:
import numpy as np

In [62]:
np.random.rand()

0.8383278583347791

In [63]:
np.random.rand(10) # rand gives values between 0 and 1

array([0.1955932 , 0.03116614, 0.24281433, 0.89695047, 0.54997799,
       0.31196507, 0.26479763, 0.46896024, 0.81110086, 0.87595885])

In [64]:
np.random.rand(10).reshape((2,5))

array([[0.3481453 , 0.19281143, 0.40142839, 0.27012993, 0.44134494],
       [0.63657043, 0.5184873 , 0.91030912, 0.60917427, 0.08084819]])

In [65]:
# Creating array from uniform distribution
new_arr=np.random.rand(5,3)
# 2 dimensional array of shape (5,3)

In [66]:
new_arr

array([[0.63768178, 0.46265783, 0.3825824 ],
       [0.26246853, 0.21915623, 0.24286342],
       [0.52140285, 0.27008798, 0.28856478],
       [0.92591214, 0.6872806 , 0.83086213],
       [0.85893904, 0.87219056, 0.85778596]])

In [67]:
np.random.rand(3,3)

array([[0.3501001 , 0.90245055, 0.88644374],
       [0.53989565, 0.77548743, 0.41167751],
       [0.01096202, 0.18898107, 0.59840431]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [68]:
# For randn, random numbbers generated will be in approximately -3 to +3 range.

In [69]:
arr1=np.random.randn(50)  # 50 observations from std normal distribution
arr1

array([ 0.07999094,  1.87082774, -0.26740952,  0.51226407,  0.44678979,
        0.45722129,  1.06760272, -0.03599028,  0.78475913,  2.12943734,
        1.55351262, -1.05721708, -0.2219807 , -2.2385073 ,  1.11172859,
        0.2821309 , -0.56249147, -0.45780069,  0.13671479,  1.00715492,
        0.46655274,  0.13437958, -0.69298212,  0.37451095, -0.43370538,
       -0.4735391 ,  0.20773179, -1.10460908, -0.30614193, -0.2483779 ,
       -0.358348  ,  1.14918429, -1.3070606 ,  1.76621819, -2.43199007,
       -0.09606797, -1.61810064,  1.66666956, -0.56048178,  0.1831253 ,
       -0.34420359,  2.17918   ,  0.46104287, -0.12994777,  0.2116878 ,
       -0.5138431 , -0.34419513,  0.47296373,  1.22744829, -0.57564819])

In [70]:
max(arr1)

2.179180001209099

In [71]:
min(arr1)

-2.431990072291125

In [72]:
np.random.randn(3,3)

array([[ 0.48450883, -0.50322699, -2.59519249],
       [-1.37510598, -1.26505722,  0.16124424],
       [-0.44575092, -0.46386464,  0.30272005]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [73]:
np.random.randint(1,100) 
# third argument is no. of values. default =1 value

22

In [74]:
np.random.randint(1,100,10)

array([23, 96, 53, 38, 78, 79, 44, 84, 14, 69])

In [75]:
np.random.randint(40,60,50) # generating 50 values between 

array([42, 47, 43, 46, 51, 46, 54, 49, 47, 40, 53, 52, 58, 46, 40, 50, 46,
       43, 43, 54, 46, 55, 54, 51, 41, 44, 49, 40, 56, 42, 47, 48, 46, 57,
       59, 57, 51, 47, 56, 47, 51, 52, 55, 52, 45, 46, 47, 50, 59, 51])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [76]:
arr = np.arange(20)
ranarr = np.random.randint(0,100,10)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [78]:
ranarr

array([83, 14,  6, 97, 51, 80,  9,  6, 29, 73])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [79]:
ranarr

array([83, 14,  6, 97, 51, 80,  9,  6, 29, 73])

In [80]:
ranarr.max() # highest element of the array

97

In [81]:
arr.max()

19

In [82]:
ranarr.argmax() ## Index location of highest element

3

In [83]:
ranarr.min() # Gives the lowest element of array

6

In [84]:
ranarr.argmin() # Index location of lowest element

2

In [85]:
ran2=ranarr.reshape(2,5)

In [86]:
ran2

array([[83, 14,  6, 97, 51],
       [80,  9,  6, 29, 73]])

In [87]:
ran2.argmax()

3

In [88]:
ran2.max()

97

# NumPy Indexing and Selection

Here we will discuss how to select elements or groups of elements from an array.

In [89]:
import numpy as np

In [90]:
#Creating sample array
arr=np.arange(0,21)

In [91]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [92]:
#Creating sample array
arr=np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [93]:
len(arr)

18

In [94]:
arr[-1]

95

In [95]:
#Get a value at an index
arr[9]

55

In [96]:
#Get values in a range
arr[1:11:2]

array([15, 25, 35, 45, 55])

## Filtering

In [97]:
import numpy as np

In [98]:
# Filtering condition 

arr=np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [99]:
arr<100

array([ True,  True, False,  True, False,  True,  True, False])

In [100]:
arr[5]

18

In [101]:
np.where(arr>100)

(array([2, 4, 7], dtype=int64),)

In [102]:
np.where(arr<100)

(array([0, 1, 3, 5, 6], dtype=int64),)

In [103]:
np.where(arr==100)

(array([], dtype=int64),)

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. It is recommended to use the comma notation for clarity.

In [104]:
import numpy as np

In [105]:
arr_2d = np.array(([1,2,3],[12,15,18],[64,96,128]))

#Show
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [106]:
arr_2d[0:,:2]

array([[ 1,  2],
       [12, 15],
       [64, 96]])

In [107]:
arr_2d[1]

array([12, 15, 18])

In [108]:
arr_2d.shape

(3, 3)

In [109]:
arr_2d[:,2]

array([  3,  18, 128])

In [110]:
arr_2d[1:,1:]

array([[ 15,  18],
       [ 96, 128]])

In [111]:
arr_2d[1,1]

15

In [112]:
arr_2d[0:2][0:2]

array([[ 1,  2,  3],
       [12, 15, 18]])

In [113]:
# Indexing column
arr_2d[:,2]

array([  3,  18, 128])

In [114]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[ 2,  3],
       [15, 18]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [115]:
arr1=np.ones((10,10))
arr1.shape

(10, 10)

In [116]:
#Set up matrix
arr2d = np.zeros(arr1.shape)  # taking shape from an existing array

In [117]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [118]:
arr2d.shape


(10, 10)

In [119]:
no_of_rows=arr2d.shape[0]  # indexing the shape tuple

In [120]:
#Set up array

for i in range(no_of_rows):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [121]:
arr2d[[6,3,8]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [122]:
arr2d[:,[2,4,6,8]]

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.],
       [8., 8., 8., 8.],
       [9., 9., 9., 9.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [123]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [125]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [126]:
arr2d[:,0]<4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

# Happy Learning!